version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=candies
    ports:
      - "5433:5432"
    networks:
      - custom

  test_db:
    container_name: "test_db"
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=candies_test
    ports:
      - "5434:5432"
    networks:
      - custom

networks:
  custom:
    driver: bridge
